export const category = [
  // 👗 Fashion & Apparel
  { value: "womens-clothing", label: "Women's Clothing" },
  { value: "mens-clothing", label: "Men's Clothing" },
  { value: "kids-clothing", label: "Kids & Baby" },
  { value: "shoes-footwear", label: "Shoes & Footwear" },
  { value: "bags-handbags", label: "Bags & Handbags" },
  { value: "jewellery", label: "Jewellery" },
  { value: "watches", label: "Watches" },
  { value: "sunglasses-eyewear", label: "Sunglasses & Eyewear" },
  { value: "activewear", label: "Activewear" },
  { value: "swimwear", label: "Swimwear" },
  { value: "outerwear", label: "Outerwear & Coats" },
  { value: "lingerie-underwear", label: "Lingerie & Underwear" },
  { value: "socks-hosiery", label: "Socks & Hosiery" },
  { value: "hats-caps", label: "Hats & Caps" },
  { value: "scarves-belts", label: "Scarves & Belts" },

  // 💻 Electronics & Tech
  { value: "smartphones", label: "Smartphones" },
  { value: "laptops-computers", label: "Laptops & Computers" },
  { value: "tablets", label: "Tablets & E-Readers" },
  { value: "tv-home-cinema", label: "TV & Home Cinema" },
  { value: "audio-headphones", label: "Audio & Headphones" },
  { value: "cameras-photography", label: "Cameras & Photography" },
  { value: "gaming", label: "Gaming" },
  { value: "smart-home", label: "Smart Home" },
  { value: "wearables", label: "Wearables" },
  { value: "printers-scanners", label: "Printers & Scanners" },
  { value: "networking", label: "Networking & Wi-Fi" },
  { value: "storage-drives", label: "Storage & Drives" },
  { value: "phone-accessories", label: "Phone Accessories" },
  { value: "pc-components", label: "PC Components" },
  { value: "refurbished", label: "Refurbished" },

  // 🏠 Home & Living
  { value: "furniture", label: "Furniture" },
  { value: "bedding-pillows", label: "Bedding & Pillows" },
  { value: "bath-towels", label: "Bath & Towels" },
  { value: "kitchen-dining", label: "Kitchen & Dining" },
  { value: "cookware-bakeware", label: "Cookware & Bakeware" },
  { value: "home-decor", label: "Home Décor" },
  { value: "rugs-flooring", label: "Rugs & Flooring" },
  { value: "curtains-blinds", label: "Curtains & Blinds" },
  { value: "lighting", label: "Lighting" },
  { value: "storage-organisation", label: "Storage & Organisation" },
  { value: "garden-outdoor", label: "Garden & Outdoor" },
  { value: "cleaning-laundry", label: "Cleaning & Laundry" },
  { value: "tools-diy", label: "Tools & DIY" },
  { value: "candles-fragrance", label: "Candles & Fragrance" },
  { value: "plants-pots", label: "Plants & Pots" },
  { value: "pet-supplies", label: "Pet Supplies" },

  // 🛒 Food & Grocery
  { value: "fresh-produce", label: "Fresh Produce" },
  { value: "meat-seafood", label: "Meat & Seafood" },
  { value: "dairy-eggs", label: "Dairy & Eggs" },
  { value: "bakery-bread", label: "Bakery & Bread" },
  { value: "frozen-foods", label: "Frozen Foods" },
  { value: "snacks-crisps", label: "Snacks & Crisps" },
  { value: "beverages", label: "Beverages" },
  { value: "coffee-tea", label: "Coffee & Tea" },
  { value: "alcohol-wine", label: "Alcohol & Wine" },
  { value: "condiments-sauces", label: "Condiments & Sauces" },
  { value: "pasta-rice-grains", label: "Pasta, Rice & Grains" },
  { value: "breakfast-cereals", label: "Breakfast & Cereals" },
  { value: "organic-natural", label: "Organic & Natural" },
  { value: "international-foods", label: "International Foods" },
  { value: "dietary-free-from", label: "Dietary & Free From" },

  // 💄 Beauty & Wellness
  { value: "skincare", label: "Skincare" },
  { value: "makeup", label: "Makeup" },
  { value: "haircare", label: "Haircare" },
  { value: "hair-styling-tools", label: "Hair Styling Tools" },
  { value: "fragrance-perfume", label: "Fragrance & Perfume" },
  { value: "body-care", label: "Body Care" },
  { value: "nail-care", label: "Nail Care" },
  { value: "mens-grooming", label: "Men's Grooming" },
  { value: "oral-care", label: "Oral Care" },
  { value: "vitamins-supplements", label: "Vitamins & Supplements" },
  { value: "sexual-wellness", label: "Sexual Wellness" },
  { value: "feminine-hygiene", label: "Feminine Hygiene" },
  { value: "baby-care", label: "Baby Care" },
  { value: "suncare-tanning", label: "Sun Care & Tanning" },
  { value: "beauty-tools-devices", label: "Beauty Tools & Devices" },

  // 🏋️ Sports & Outdoors
  { value: "gym-fitness", label: "Gym & Fitness" },
  { value: "running", label: "Running" },
  { value: "cycling", label: "Cycling" },
  { value: "swimming-watersports", label: "Swimming & Watersports" },
  { value: "team-sports", label: "Team Sports" },
  { value: "racket-sports", label: "Racket Sports" },
  { value: "golf", label: "Golf" },
  { value: "yoga-pilates", label: "Yoga & Pilates" },
  { value: "hiking-camping", label: "Hiking & Camping" },
  { value: "climbing", label: "Climbing" },
  { value: "skiing-snowboarding", label: "Skiing & Snowboarding" },
  { value: "martial-arts", label: "Martial Arts" },
  { value: "sports-nutrition", label: "Sports Nutrition" },
  { value: "sportswear", label: "Sportswear" },
  { value: "sports-shoes", label: "Sports Shoes" },
  { value: "fan-shop", label: "Fan Shop" },

  // 🏷️ Global
  { value: "sale", label: "Sale" },
  { value: "new-arrivals", label: "New Arrivals" },
  { value: "gift-cards", label: "Gift Cards" },
];
